//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OgrenciTab()
        {
            this.OgrenciDersTab = new HashSet<OgrenciDersTab>();
        }
    
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string KayitTarih { get; set; }
        public Nullable<int> OgrenciNo { get; set; }
        public string DTarih { get; set; }
        public string Bolum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDersTab> OgrenciDersTab { get; set; }
    }
}
